version: '3.8'

services:
  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pilares
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  rasa:
    build: ./chatbot/rasa
    ports:
      - "5005:5005"

volumes:
  db_data: