# config.yml - Rasa Configuration
recipe: default.v1
language: "es"  # Spanish language configuration

# Pipeline configuration for NLU
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "word"
    min_ngram: 1
    max_ngram: 3
  - name: DIETClassifier  # Dual Intent Entity Transformer
    epochs: 100
    hidden_layers_sizes:
      text: [256, 128]
    entity_recognition: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
    retrieval_intent: "faq"
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.5

# Policy configuration for dialogue management
policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: TEDPolicy  # Transformer-based Embedding Dialogue Policy
    max_history: 5
    epochs: 100
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true

# Custom components
components:
  - name: "components.custom_components.PILARESActionValidator"

# Configuration for training
training:
  batch_strategy: "balanced"
  evaluation_interval: 5
  max_steps: 1000
  dropout_rate: 0.2

# Logging configuration
log_level: INFO